

PATCH_SIZE = (128,) * 3
MOUSE_N = 6

TRAIN_MOUSE_INDEX = [1,2,3,4] 
TEST_MOUSE_INDEX  = [0,5]

RESULT_DIR = "./training_diagnostics/"

SAVE_TRAIN_IMG = 0


MAX_EPOCH = 200
SAVE_EVERY_N_EPOCH = 1
LAMBDA_WEIGHT_REG = 0.01
TV_ALPHA = 5e-9

# CHANNELS_N = 16  # for default V-net

# PATCH_TRAIN_N = 9702
# PATCH_TEST_N = 48
